from .player import Player
from .tit_for_tat import Tit_For_Tat
from .generous_TFT import Generous_Tit_For_Tat
from .random_play import Random
from .friedman import Friedman
from .sample import Sample
from .joss import Joss
from .tester import Tester
from .alwayscoop import AlwaysCoop
from .cheater import Cheater
